CS2103AUG2016-T10-C2/main

.project
src/main/java/seedu/address/logic/parser/TMParser.java
src/test/java/seedu/address/logic/parser/TMParserTest.java

Supports adding somedays and deadlines; events not yet supported. Closes #4 and #25.

Parser add tasks

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/TMParser.java
src/test/java/seedu/address/logic/parser/TMParserTest.java

Added delete functionality to parser

---

src/main/java/seedu/address/model/task/AbstractTask.java
src/main/java/seedu/address/model/task/DeadlineTask.java
src/main/java/seedu/address/model/task/SomedayTask.java
src/main/java/seedu/address/model/task/TMReadOnlyTask.java

AbstractTask defines abstract getters and setters for name, start date, end date, status, task type and tag list. Getters for start date and end date return optionals since some task may not have these fields.
Deadlines, somedays and (eventually) events extend from the abstract class and implement the tmreadonlytask interface.

Created AbstractTask

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/parser/ParserTest.java

* Delete command accepts multiple indices
* List command with no args should work

Fix parser

---

build.gradle
src/main/java/seedu/address/logic/parser/Parser.java

NLP parsing for deadline tasks, subject to Natty's limitations

Date parsing

---

src/main/java/seedu/address/logic/parser/Parser.java
src/test/java/guitests/SelectCommandTest.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/testutil/TestTask.java

Fix test cases

---

src/main/java/seedu/address/ui/DeadlineTaskCard.java
src/main/java/seedu/address/ui/EventTaskCard.java
src/main/java/seedu/address/ui/TaskListPanel.java
src/main/resources/view/DeadlineTaskCard.fxml
src/main/resources/view/EventTaskCard.fxml

This should display tasks according to type. Have a look. After merging I can start fixing the test

all task cards added

---

src/main/java/seedu/address/commons/exceptions/IncorrectCommandException.java
src/main/java/seedu/address/logic/commands/DoneCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/test/java/guitests/EditCommandTest.java
src/test/java/seedu/address/logic/parser/ParserTest.java

i changed the parser for delete a little for reuse in done

Done command

---

src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/storage/XmlSerializableTaskManager.java
src/test/data/XmlUtilTest/validTaskManager.xml
src/test/java/seedu/address/commons/util/XmlUtilTest.java
src/test/java/seedu/address/logic/LogicManagerTest.java

* Changed validTaskManager to follow task manager format instead of address book
* Commented out select command tests

Pass more tests

---

src/main/resources/view/DarkTheme.css
src/main/resources/view/NewMainWindow.fxml

change the border padding for @joycelynng hahah :)

change ui padding for Joycelyn :)

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/test/java/seedu/address/logic/LogicManagerTest.java

* Case-insensitive
* Comma-delimited
* Supports substring search. eg. `find go` will list a task with name 'got milk?'
Closes #14

Find command working

---

src/main/java/seedu/address/model/task/TaskFilter.java
src/main/resources/view/NewMainWindow.fxml

change ui and predicate

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/task/TaskFilter.java

List improve

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/task/TaskFilter.java
src/main/java/seedu/address/ui/DeadlineTaskCard.java
src/main/java/seedu/address/ui/EventTaskCard.java
src/main/java/seedu/address/ui/NewMainWindow.java
src/main/java/seedu/address/ui/SomedayTaskCard.java
src/main/resources/view/DeadlineTaskCard.fxml
src/main/resources/view/EventTaskCard.fxml
src/main/resources/view/SomedayTaskCard.fxml

Reverts CS2103AUG2016-T10-C2/main#101

Revert "Ui enhancing"

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/task/TaskFilter.java

Reverts CS2103AUG2016-T10-C2/main#100

Revert "List improve"

---

src/main/java/seedu/address/model/task/ReadOnlyTask.java
src/main/java/seedu/address/model/task/TaskDateTimeFormatter.java
src/main/java/seedu/address/ui/DeadlineTaskCard.java
src/main/java/seedu/address/ui/EventTaskCard.java
src/main/java/seedu/address/ui/SomedayTaskCard.java
src/main/resources/view/DeadlineTaskCard.fxml
src/main/resources/view/EventTaskCard.fxml
src/main/resources/view/SomedayTaskCard.fxml

Format time display and edit cards

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/task/Task.java
src/test/java/guitests/guihandles/DeadlineTaskCardHandle.java
src/test/java/guitests/guihandles/EventTaskCardHandle.java
src/test/java/guitests/guihandles/GuiHandle.java
src/test/java/guitests/guihandles/TaskListPanelHandle.java
src/test/java/seedu/address/testutil/TestUtil.java

someday -> deadline -> event possible but not the other way round yet
close #106

Task upgrading possible

---

src/test/java/guitests/ChangeStatusCommandTest.java
src/test/java/seedu/address/testutil/TypicalTestTasks.java

fix pending command

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/CommandHistoryManager.java

Pressing the up and down arrow keys will show the previous and next commands entered respectively. Slightly buggy: sometimes the key needs to be pressed twice for the command to change. On the first press only the text cursor moves but the command string does not change.
Closes #65

Command history

---

src/main/resources/view/DeadlineTaskCard.fxml
src/main/resources/view/EventTaskCard.fxml
src/main/resources/view/SomedayTaskCard.fxml

edit cards

---

src/main/java/seedu/address/logic/commands/RedoCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/storage/XmlAdaptedTask.java
src/main/java/seedu/address/ui/CommandBox.java

Fix find cmd

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/DeadlineTaskCard.java
src/main/java/seedu/address/ui/EventTaskCard.java
src/main/java/seedu/address/ui/SomedayTaskCard.java
src/main/resources/view/DeadlineTaskCard.fxml
src/main/resources/view/EventTaskCard.fxml
src/main/resources/view/SomedayTaskCard.fxml

changed command box background and put back cursor when error

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/model/tag/UniqueTagList.java

Parser tags

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/test/java/guitests/CommandBoxTest.java
src/test/java/seedu/address/logic/parser/ParserTest.java
src/test/java/seedu/address/testutil/TestTask.java

Commands like `add from 5pm today 'play frisbee' to 6pm tomorrow` now parse properly

Make add command format more flexible

---

src/main/java/seedu/address/logic/parser/Parser.java

Parser can replace command input with aliases. Not linked to actual class

alias parsing support, not linked to command

---

src/main/java/seedu/address/logic/parser/DateParser.java
src/test/java/seedu/address/logic/parser/DateParserTest.java
src/test/java/seedu/address/logic/parser/ParserTest.java

Reject invalid dates

---

.settings/org.eclipse.buildship.core.prefs
build.gradle
src/main/java/seedu/address/commons/events/ui/ViewTabRequestEvent.java
src/main/java/seedu/address/logic/commands/TabCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/UiManager.java
src/main/resources/view/MainWindow.fxml
src/test/java/guitests/ChangeStatusCommandTest.java
src/test/java/seedu/address/logic/parser/ParserTest.java

@KnytJC to implement functionality in execute() method of command.
Closes #191, #192

Added tab command and parser support for it

---

src/main/java/seedu/address/logic/parser/DateParser.java
src/test/java/guitests/ChangeStatusCommandTest.java
src/test/java/seedu/address/logic/parser/DateParserTest.java

Add containsDate method to DateParser

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/ChangeStatusCommand.java
src/main/java/seedu/address/logic/commands/DeleteAliasCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/alias/ReadOnlyAlias.java
src/test/java/guitests/ChangeStatusCommandTest.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/parser/ParserTest.java

Have not written DeleteAliasCommandTest.

Delete alias command
